services:
  et5bb5xy6l:
    container_name: et5bb5xy6l_app
    image: ghcr.io/mr-devloper005/ideovera.com:latest
    env_file:
      - .env
    network_mode: bridge
    restart: always
    ports:
      - "127.0.0.1:3210:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/"]
      interval: 5m
      timeout: 3s
      retries: 2
